export type { DialectId } from "../core/types.ts";

/** Logical SQL types supported by the type catalog. */
export type SqlTypeName =
  | "boolean"
  | "int2"
  | "int4"
  | "int8"
  | "float4"
  | "float8"
  | "numeric"
  | "text"
  | "varchar"
  | "char"
  | "bytea"
  | "blob"
  | "date"
  | "time"
  | "timestamp"
  | "timestamptz"
  | "json"
  | "jsonb"
  | "uuid"
  | "array"
  | "enum"
  | "inet"
  | "cidr"
  | "interval"
  | "xml"
  | "null";
